# Generated by Django 4.1.4 on 2023-01-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
