# Generated by Django 4.1.4 on 2022-12-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lessons',
        ),
    ]
