# Generated by Django 4.1.4 on 2023-01-18 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_remove_lesson_profile'),
        ('user_profile', '0005_remove_profile_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lessons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', unique=True),
        ),
    ]
