# Generated by Django 4.1.4 on 2023-01-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profile_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lessons',
        ),
    ]
