# Generated by Django 4.1.4 on 2023-01-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_profile_lessons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
