# Generated by Django 4.1.4 on 2023-01-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_rename_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
