# Generated by Django 4.1.4 on 2023-01-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
