# Generated by Django 4.1.4 on 2023-01-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_rename_user_l_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='login_user',
        ),
    ]
