# Generated by Django 4.1.4 on 2023-01-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_password_alter_user_username'),
        ('user_profile', '0016_alter_profile_login_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='login_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
