# Generated by Django 4.1.4 on 2022-12-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='User',
        ),
    ]
