# Generated by Django 4.1.4 on 2022-12-31 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_profile_lessons'),
        ('lesson', '0002_remove_lesson_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile'),
        ),
    ]
