# Generated by Django 4.1.4 on 2023-01-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_lesson_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='profile',
        ),
    ]
