# Generated by Django 4.1.4 on 2023-01-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_lesson_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='profile',
        ),
    ]
