# Generated by Django 4.1.4 on 2023-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_lesson_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='class_date',
            field=models.CharField(choices=[('1', 'Sun'), ('2', 'Mon'), ('3', 'Tus'), ('4', 'Wen'), ('5', 'Thu'), ('6', 'Fri'), ('7', 'Sut')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='class_hour',
            field=models.CharField(choices=[('1', '7_9'), ('2', '9_11'), ('3', '11_13'), ('4', '13_15'), ('5', '15_17'), ('6', '17_19'), ('7', '19_21')], default=None, max_length=1),
        ),
    ]
