# Generated by Django 4.1.4 on 2023-01-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_remove_lesson_time_lesson_class_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='class_date',
            field=models.CharField(choices=[('1', 'Sun'), ('2', 'Mon'), ('3', 'Tus'), ('4', 'Wen'), ('5', 'Thu'), ('6', 'Fri'), ('7', 'Sut')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_hour',
            field=models.CharField(choices=[('1', '7_9'), ('2', '9_11'), ('3', '11_13'), ('4', '13_15'), ('5', '15_17'), ('6', '17_19'), ('7', '19_21')], default='', max_length=1),
        ),
    ]
