# Generated by Django 4.1.4 on 2023-01-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_lesson_class_date_alter_lesson_class_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.CharField(choices=[('1', 'Sun'), ('2', 'Mon'), ('3', 'Tus'), ('4', 'Wen'), ('5', 'Thu'), ('6', 'Fri'), ('7', 'Sut')], default='', max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='class_date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.date'),
        ),
    ]
