# Generated by Django 4.1.4 on 2023-01-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_date_remove_lesson_class_date_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lesson.date'),
        ),
    ]
