# Generated by Django 4.1.4 on 2023-01-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_alter_lesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='class_date',
            field=models.CharField(choices=[('1', 'Sun'), ('2', 'Mon'), ('3', 'Tus'), ('4', 'Wen'), ('5', 'Thu'), ('6', 'Sut'), ('7', 'Sut_Mon'), ('8', 'Sut_Wen'), ('9', 'Mon_Wen'), ('10', 'Sun_Tus'), ('11', 'Sun_Thu'), ('12', 'Ths_Thu'), ('13', 'Sun_Ths_Thu'), ('14', 'Sut,Mon,Wen')], default='', max_length=11),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
