# Generated by Django 4.1.4 on 2023-01-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_remove_lesson_date_lesson_class_date_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='class_date',
            field=models.CharField(choices=[('1', 'Sun'), ('2', 'Mon'), ('3', 'Tus'), ('4', 'Wen'), ('5', 'Thu'), ('6', 'Sut'), ('7', 'Sut_Mon'), ('8', 'Sut_Wen'), ('9', 'Mon_Wen'), ('10', 'Sun_Tus'), ('11', 'Sun_Thu'), ('12', 'Ths_Thu'), ('13', 'Sun_Ths_Thu'), ('14', 'Sut_Mon_Wen')], default='', max_length=11),
        ),
    ]
