# Generated by Django 4.1.4 on 2023-01-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_alter_lesson_class_date_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='class_date',
        ),
    ]
