# Generated by Django 4.1.4 on 2023-01-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_remove_lesson_class_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='class_hour',
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('0', 'Sat'), ('1', 'Sun'), ('2', 'Mon'), ('3', 'Tue'), ('4', 'Wed'), ('5', 'Thu')], default='', max_length=1),
        ),
    ]
