# Generated by Django 4.1.4 on 2023-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0016_remove_lesson_class_hour_alter_day_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='class_hour',
            field=models.CharField(choices=[('1', '7_9'), ('2', '9_11'), ('3', '11_13'), ('4', '13_15'), ('5', '15_17'), ('6', '17_19'), ('7', '19_21')], default='', max_length=1),
        ),
    ]
