# Generated by Django 4.1.4 on 2023-01-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('lesson', '0017_lesson_class_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_lessons', to='schedule.table'),
        ),
    ]
